Repository SIMDE-ULL/SIMDE, pull requests merged in 2024-03, with the labels that each got.

#102 chore: configure allcontributors
  .all-contributorsrc
  README.md
Labels: enhancement

#115 chore: rewrite README, add CONTRIBUTING, sort package.json
  CONTRIBUTING.md
  README.md
  assets/exec.gif
  package.json
  yarn.lock
Labels: documentation

#126 fix: review i18n labels
  public/locales/en/common.json
  public/locales/es/common.json
  src/i18n.ts
  src/interface/components/Common/Modal/BatchModalComponent.tsx
  src/interface/components/Superescalar/modal/LoadModalComponent.tsx
  src/interface/components/Superescalar/modal/OptionsModalComponent.tsx
  src/interface/components/Superescalar/modal/SuperescalarLoadContentModalComponent.tsx
  src/interface/components/Superescalar/navbar/FileBarComponent.tsx
  src/interface/components/VLIW/modal/BatchModalComponent.tsx
  src/interface/components/VLIW/modal/OptionsModalComponent.tsx
  src/interface/components/VLIW/modal/VLIWLoadContentModalComponent.tsx
  src/interface/components/VLIW/modal/VLIWLoadModalComponent.tsx
  src/interface/components/VLIW/navbar/VLIWFileBarComponent.tsx
Labels: bug, i18n

#127 chore: remove node tsconfig
  tsconfig.json
  tsconfig.node.json
Labels: enhancement

#130 fix: repair SuperscalarConfigModal layout
  public/locales/en/common.json
  public/locales/es/common.json
  src/core/Common/Machine.ts
  src/core/Superescalar/Superescalar.ts
  src/integration/superescalar-integration.ts
  src/interface/components/Superescalar/SuperescalarComponent.tsx
  src/interface/components/Superescalar/modal/OptionsModalComponent.tsx
  src/interface/components/Superescalar/modal/SuperescalarConfigModal.tsx
  src/interface/components/Superescalar/modal/SuperescalarConfigModalComponent.tsx
  src/interface/components/Superescalar/tab/StatsTabComponent.tsx
  src/interface/reducers/index.ts
Labels: bug, ui

#134 refactor(i18n): reorganize keys and finish translations
  public/locales/en/common.json
  public/locales/es/common.json
  src/interface/actions/table-actions.ts
  src/interface/components/Superescalar/CodeComponent.tsx
  src/interface/components/Superescalar/FunctionalUnitComponent.tsx
  src/interface/components/Superescalar/ReserveStationComponent.tsx
  src/interface/components/Superescalar/modal/SuperescalarConfigModal.tsx
  src/interface/components/Superescalar/tab/GeneralTabComponent.tsx
  src/interface/components/Superescalar/tab/RegistersTabComponent.tsx
  src/interface/components/Superescalar/tab/StatsTabComponent.tsx
  src/interface/components/VLIW/CodeComponent.tsx
  src/interface/components/VLIW/FunctionalUnitComponent.tsx
  src/interface/components/VLIW/TableComponent.tsx
  src/interface/components/VLIW/modal/VLIWConfigModalComponent.tsx
  src/interface/components/VLIW/tab/GeneralVLIWTabComponent.tsx
  src/interface/components/VLIW/tab/RegistersVLIWTabComponent.tsx
Labels: enhancement, i18n
