Repository SIMDE-ULL/SIMDE, pull requests merged in 2024-04, with the labels that each got.

#139 chore: enable tsconfig path resolution aliases for vite
  package.json
  pnpm-lock.yaml
  tsconfig.json
  vite.config.ts
Labels: enhancement, core-dev, refactor

#143 feat(parser): make line count header optional
  src/core/Common/CodeParser.ts
  src/core/VLIW/VLIWCode.ts
  src/core/VLIW/VLIWParser.ts
  src/interface/components/Superescalar/modal/LoadModalComponent.tsx
  src/interface/components/VLIW/modal/VLIWLoadModalComponent.tsx
  src/test/unit/core/Common/Code.spec.ts
  src/test/unit/core/VLIW/VLIWParser.spec.ts
Labels: bug, enhancement, core-dev

#146 refactor(interface): update VLIW Load component
  src/interface/components/VLIW/modal/VLIWLoadModalComponent.tsx
Labels: enhancement, refactor, ui

#151 fix: accept CRLF newlines
  src/core/Common/CodeParser.ts
  src/test/unit/core/Common/Code.spec.ts
Labels: bug, parsers

#158 feat: implement direct-mapped cache, cache config modal
  public/locales/en/common.json
  public/locales/es/common.json
  src/core/Common/Cache.ts
  src/core/Common/Machine.ts
  src/core/Common/Memory.ts
  src/core/Superscalar/Superscalar.ts
  src/core/VLIW/VLIW.ts
  src/integration/superscalar-integration.ts
  src/integration/vliw-integration.ts
  src/interface/components/Common/Modal/BatchModalComponent.tsx
  src/interface/components/Superscalar/modal/SuperscalarConfigModal.tsx
  src/interface/components/VLIW/modal/BatchModalComponent.tsx
  src/interface/components/VLIW/modal/VLIWConfigModalComponent.tsx
  src/interface/utils/constants.ts
  src/test/functional/Superscalar/iteratelist.spec.ts
  src/test/functional/Superscalar/loop.spec.ts
  src/test/functional/Superscalar/speculativenosideeffects.spec.ts
  src/test/functional/VLIW/loop.spec.ts
  src/test/functional/VLIW/multiwayvliw.spec.ts
  src/test/unit/core/Common/Cache.spec.ts
Labels: enhancement, core-dev, feature, ui
